"""empty message

Revision ID: 80c398754da2
Revises: 51f5ccfba190
Create Date: 2018-05-22 21:25:11.665858

"""

# revision identifiers, used by Alembic.
revision = '80c398754da2'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
